//! Raw bindings to the subset of Ditto's C ABI (`dittoffi`) that the backend
//! uses.
//!
//! Source of truth: the `extern "C"` header embedded in the Ditto C++ SDK's
//! `Ditto.h` (include guard `__RUST_DITTOFFI__`), generated by safer-ffi for
//! each release. The declarations below were transcribed from SDK version
//! `DITTO_SDK_VERSION` (see `build.rs`); `scripts/ditto-abi-check.sh` prints
//! the same declarations from any release so a bump can be diffed. The ABI
//! is Ditto-internal and has no stability promise: treat every SDK upgrade
//! as a re-verification of this file.
//!
//! Conventions, as safer-ffi emits them:
//! - `*_throws` functions return a `Result*` struct: `error` is non-null on
//!   failure (free with [`dittoffi_error_free`]), `success` is valid
//!   otherwise.
//! - Slices are `{ptr, len}`. Borrowed slices (`SliceRef`) are ours;
//!   owned slices (`SliceBoxed`) come from Ditto and are returned with
//!   [`ditto_c_bytes_free`]. Owned C strings go back via
//!   [`ditto_c_string_free`].
//! - Boxed callbacks are `{env_ptr, call, free}`; Ditto calls `free` exactly
//!   once when it is done with the callback.
#![allow(dead_code, non_camel_case_types)]

use std::os::raw::{c_char, c_void};

/// `CDitto_t` — an opaque Ditto instance.
#[repr(C)]
pub struct CDitto {
    _private: [u8; 0],
}

/// `dittoffi_error_t` — an opaque error object.
#[repr(C)]
pub struct Error {
    _private: [u8; 0],
}

/// `dittoffi_query_result_t`
#[repr(C)]
pub struct QueryResult {
    _private: [u8; 0],
}

/// `dittoffi_query_result_item_t`
#[repr(C)]
pub struct QueryResultItem {
    _private: [u8; 0],
}

/// `dittoffi_sync_subscription_t`
#[repr(C)]
pub struct SyncSubscription {
    _private: [u8; 0],
}

/// `dittoffi_store_observer_t`
#[repr(C)]
pub struct StoreObserver {
    _private: [u8; 0],
}

/// `CLoginProvider_t`
#[repr(C)]
pub struct LoginProvider {
    _private: [u8; 0],
}

/// `slice_ref_uint8_t` — a borrowed byte slice.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SliceRef {
    pub ptr: *const u8,
    pub len: usize,
}

impl SliceRef {
    pub fn from_bytes(bytes: &[u8]) -> Self {
        Self {
            ptr: bytes.as_ptr(),
            len: bytes.len(),
        }
    }

    /// The representation safer-ffi uses for `Option<c_slice::Ref>::None`.
    pub const NONE: Self = Self {
        ptr: std::ptr::null(),
        len: 0,
    };
}

/// `slice_boxed_uint8_t` — an owned byte slice allocated by Ditto.
#[repr(C)]
pub struct SliceBoxed {
    pub ptr: *mut u8,
    pub len: usize,
}

/// `TransportConfigMode_t`
#[repr(C)]
#[derive(Clone, Copy)]
pub enum TransportConfigMode {
    PlatformDependent = 0,
    PlatformIndependent = 1,
}

/// `CLogLevel_t`
#[repr(C)]
#[derive(Clone, Copy)]
pub enum CLogLevel {
    Error = 1,
    Warning = 2,
    Info = 3,
    Debug = 4,
    Verbose = 5,
}

/// `dittoffi_error_code_t` is a C enum; only its integer value is used here.
pub type ErrorCode = i32;

/// `dittoffi_result_void_t`
#[repr(C)]
pub struct ResultVoid {
    pub error: *mut Error,
}

/// `dittoffi_result_CDitto_ptr_t`
#[repr(C)]
pub struct ResultDitto {
    pub error: *mut Error,
    pub success: *mut CDitto,
}

/// `dittoffi_result_dittoffi_query_result_ptr_t`
#[repr(C)]
pub struct ResultQueryResult {
    pub error: *mut Error,
    pub success: *mut QueryResult,
}

/// `dittoffi_result_dittoffi_sync_subscription_ptr_t`
#[repr(C)]
pub struct ResultSyncSubscription {
    pub error: *mut Error,
    pub success: *mut SyncSubscription,
}

/// `dittoffi_result_dittoffi_store_observer_ptr_t`
#[repr(C)]
pub struct ResultStoreObserver {
    pub error: *mut Error,
    pub success: *mut StoreObserver,
}

/// `ArcDynFn0_void_t` — `Arc<dyn Send + Sync + Fn()>`. Handed to observer
/// callbacks as the "signal next" function; the receiver owns one strong
/// reference and must `release` it.
#[repr(C)]
pub struct ArcDynFn0 {
    pub env_ptr: *mut c_void,
    pub call: Option<unsafe extern "C" fn(*mut c_void)>,
    pub release: Option<unsafe extern "C" fn(*mut c_void)>,
    pub retain: Option<unsafe extern "C" fn(*mut c_void)>,
}

/// `BoxDynFnMut3_void_dittoffi_query_result_ptr_ArcDynFn0_void_t` — the
/// store observer callback: `Box<dyn FnMut(*mut QueryResult, ArcDynFn0)>`.
#[repr(C)]
pub struct StoreObserverCallback {
    pub env_ptr: *mut c_void,
    pub call: unsafe extern "C" fn(*mut c_void, *mut QueryResult, ArcDynFn0),
    pub free: unsafe extern "C" fn(*mut c_void),
}

extern "C" {
    // --- instance lifecycle -------------------------------------------------

    /// `dittoffi_result_CDitto_ptr_t dittoffi_ditto_open_throws(slice_ref_uint8_t config_cbor, TransportConfigMode_t, char const *default_root_directory)`
    pub fn dittoffi_ditto_open_throws(
        config_cbor: SliceRef,
        transport_config_mode: TransportConfigMode,
        default_root_directory: *const c_char,
    ) -> ResultDitto;

    /// `void ditto_free(CDitto_t *ditto)`
    pub fn ditto_free(ditto: *mut CDitto);

    /// `int32_t ditto_disable_sync_with_v3(CDitto_t const *ditto)` — 0 on success.
    pub fn ditto_disable_sync_with_v3(ditto: *const CDitto) -> i32;

    /// `dittoffi_result_void_t dittoffi_ditto_set_offline_only_license_token_throws(CDitto_t const *, char const *license)`
    pub fn dittoffi_ditto_set_offline_only_license_token_throws(
        ditto: *const CDitto,
        license: *const c_char,
    ) -> ResultVoid;

    /// `dittoffi_result_void_t dittoffi_ditto_try_start_sync(CDitto_t const *)`
    pub fn dittoffi_ditto_try_start_sync(ditto: *const CDitto) -> ResultVoid;

    /// `void dittoffi_ditto_stop_sync(CDitto_t const *)`
    pub fn dittoffi_ditto_stop_sync(ditto: *const CDitto);

    // --- DQL ---------------------------------------------------------------

    /// `dittoffi_result_dittoffi_query_result_ptr_t dittoffi_try_exec_statement(CDitto_t const *, char const *statement, slice_ref_uint8_t args_cbor)`
    pub fn dittoffi_try_exec_statement(
        ditto: *const CDitto,
        statement: *const c_char,
        args_cbor: SliceRef,
    ) -> ResultQueryResult;

    /// `size_t dittoffi_query_result_item_count(dittoffi_query_result_t const *)`
    pub fn dittoffi_query_result_item_count(result: *const QueryResult) -> usize;

    /// `dittoffi_query_result_item_t *dittoffi_query_result_item_at(dittoffi_query_result_t const *, size_t idx)`
    pub fn dittoffi_query_result_item_at(
        result: *const QueryResult,
        idx: usize,
    ) -> *mut QueryResultItem;

    /// `slice_boxed_uint8_t dittoffi_query_result_item_cbor(dittoffi_query_result_item_t const *)`
    pub fn dittoffi_query_result_item_cbor(item: *const QueryResultItem) -> SliceBoxed;

    /// `void dittoffi_query_result_item_free(dittoffi_query_result_item_t *)`
    pub fn dittoffi_query_result_item_free(item: *mut QueryResultItem);

    /// `void dittoffi_query_result_free(dittoffi_query_result_t *)`
    pub fn dittoffi_query_result_free(result: *mut QueryResult);

    // --- sync subscriptions ------------------------------------------------

    /// `dittoffi_result_dittoffi_sync_subscription_ptr_t dittoffi_sync_register_subscription_throws(CDitto_t const *, char const *query, slice_ref_uint8_t query_args_cbor)`
    pub fn dittoffi_sync_register_subscription_throws(
        ditto: *const CDitto,
        query: *const c_char,
        query_args_cbor: SliceRef,
    ) -> ResultSyncSubscription;

    /// `void dittoffi_sync_subscription_cancel(dittoffi_sync_subscription_t const *)`
    pub fn dittoffi_sync_subscription_cancel(subscription: *const SyncSubscription);

    /// `void dittoffi_sync_subscription_free(dittoffi_sync_subscription_t *)`
    pub fn dittoffi_sync_subscription_free(subscription: *mut SyncSubscription);

    // --- store observers ---------------------------------------------------

    /// `dittoffi_result_dittoffi_store_observer_ptr_t dittoffi_store_register_observer_throws(CDitto_t const *, char const *query, slice_ref_uint8_t query_args_cbor, BoxDynFnMut3_... callback)`
    pub fn dittoffi_store_register_observer_throws(
        ditto: *const CDitto,
        query: *const c_char,
        query_args_cbor: SliceRef,
        callback: StoreObserverCallback,
    ) -> ResultStoreObserver;

    /// `void dittoffi_store_observer_cancel(dittoffi_store_observer_t const *)`
    pub fn dittoffi_store_observer_cancel(observer: *const StoreObserver);

    /// `void dittoffi_store_observer_free(dittoffi_store_observer_t *)`
    pub fn dittoffi_store_observer_free(observer: *mut StoreObserver);

    // --- presence ----------------------------------------------------------

    /// `slice_boxed_uint8_t dittoffi_presence_graph(CDitto_t const *)` — JSON `PresenceGraph`.
    pub fn dittoffi_presence_graph(ditto: *const CDitto) -> SliceBoxed;

    // --- authentication (server connect mode) ------------------------------

    /// `CLoginProvider_t *ditto_auth_client_make_login_provider(void *ctx, void (*retain)(void *), void (*release)(void *), void (*expiring_cb)(void *, uint32_t))`
    pub fn ditto_auth_client_make_login_provider(
        ctx: *mut c_void,
        retain: unsafe extern "C" fn(*mut c_void),
        release: unsafe extern "C" fn(*mut c_void),
        expiring_cb: unsafe extern "C" fn(*mut c_void, u32),
    ) -> *mut LoginProvider;

    /// `void ditto_auth_set_login_provider(CDitto_t const *, CLoginProvider_t *login_provider)`
    pub fn ditto_auth_set_login_provider(ditto: *const CDitto, login_provider: *mut LoginProvider);

    /// `int32_t ditto_auth_client_login_with_token(CDitto_t *, char const *token, char const *provider)`
    pub fn ditto_auth_client_login_with_token(
        ditto: *mut CDitto,
        token: *const c_char,
        provider: *const c_char,
    ) -> i32;

    // --- logging -----------------------------------------------------------

    /// `void ditto_logger_enabled(bool enabled)`
    pub fn ditto_logger_enabled(enabled: bool);

    /// `void ditto_logger_minimum_log_level(CLogLevel_t log_level)`
    pub fn ditto_logger_minimum_log_level(log_level: CLogLevel);

    // --- errors and memory -------------------------------------------------

    /// `dittoffi_error_code_t dittoffi_error_code(dittoffi_error_t const *)`
    pub fn dittoffi_error_code(error: *const Error) -> ErrorCode;

    /// `char *dittoffi_error_description(dittoffi_error_t const *)` — free with `ditto_c_string_free`.
    pub fn dittoffi_error_description(error: *const Error) -> *mut c_char;

    /// `void dittoffi_error_free(dittoffi_error_t *)`
    pub fn dittoffi_error_free(error: *mut Error);

    /// `void ditto_c_string_free(char *s)`
    pub fn ditto_c_string_free(s: *mut c_char);

    /// `void ditto_c_bytes_free(slice_boxed_uint8_t bytes)`
    pub fn ditto_c_bytes_free(bytes: SliceBoxed);
}
